### ISSUE TITLE
Upload attachment?

### ISSUE THREAD

**Issue by tetsujin1979** [uakihir0/bsky4j#5]
Thank you for the work on the library, it's exactly what I'm looking for!

I'm just wondering if it's possible to attach an image to a FeedPostRequest object, when posting a request?

**Comment by uakihir0** [comment]
Hi.

Please refer to the test code.
https://github.com/uakihir0/bsky4j/blob/main/core/src/test/java/bsky4j/bsky/feed/PostTest.java#L53

**Comment by tetsujin1979** [comment]
Thank you, I found that right after I posted!
