### ISSUE TITLE
FacetUtil.extractFacets() removes https:// - posted url isn't completely clickable

### ISSUE THREAD

**Issue by tnaden** [uakihir0/bsky4j#9]
Sorry if this is on my end, but I can't get posting with a link to work properly.

Reproduce:

`FacetUtil.extractFacets(text).getRichTextFacets(new HashMap<>());`
With for example text = `"something something https://www.avalidlink.com/something/123456"`
Posting using the `FeedPostRequest.builder()` with `facets(text)` and `facets(list)`.
Results in a post with only start of URL being a link. 

For example above the missing character count appear to match `https://` (8 chars) which leads me to believe its the `linkFacet `method that is the issue. However I have one more example:
"Bluesky - 𝕏 alternative - is now available as an invite-only beta" + newline + a link to a forum thread
The Bluesky post is missing 8+2 characters of the link.

**Comment by uakihir0** [comment]
@tnaden 

Thanks for reporting back.
Bsky4j shortens the link to post if the link is somewhat long, and when it does, it omits the protocol part and the letters after it.

```
Before: https://www.avalidlink.com/something/123456
After: www.avalidlink.com/somethin...
```

I couldn't figure out the miscalculation part at hand, so it would be helpful if you could provide me with the URL of the corresponding Bluesky post.

**Comment by tnaden** [comment]
@uakihir0 Thank you for responding. Please see below code and example posts.

The string and facets:
```
String text = UtilityM.removeTagsAndEncode(
   gd.getEraBSThreadBuffer().firstEntry().getValue()) + "\n" + "https://www.resetera.com/threads/" 
   + gd.getEraBSThreadBuffer().firstEntry().getKey();
List<RichtextFacet> list = FacetUtil.extractFacets(text).getRichTextFacets(new HashMap<>());
```

My UtilityM doesn't do anything that would cause this(?):
`return toFix.replace("\\@", "(at)").replace("\\#", "(hash)").replace("–", "-");`
This is a leftover from when I posted to Twitter,  the @ part still does something.

Resulting text: 
`Bluesky - 𝕏 alternative - is now available as an invite-only beta\nhttps://www.resetera.com/threads/691999`
Code added attempt to fix issue, as I noticed the ByteEnd didn't extend to the end of the array:
`list.get(list.size()-1).getIndex().setByteEnd(text.length());`
This doesn't always fix the link so it extends to the end of the post, but almost always.
```
gd.getBlueskyHome().feed().post(FeedPostRequest.builder()
   .accessJwt(gd.getBlueskyAccessJwt())
   .text(text)
   .facets(list)
   .build());
```

Resulting post examples (with fix code): 
https://bsky.app/profile/nesbotetc.bsky.social/post/3kamxy5dlkj2m
https://bsky.app/profile/nesbotetc.bsky.social/post/3kap4vmgocs2r

Unfortunately I don't have any posts without the fix code to show, but the link part of the post is shorter and the issue way more frequent.

**Comment by uakihir0** [comment]
@tnaden 

The text to be specified for "text" is different, so please check there.
https://github.com/uakihir0/bsky4j/blob/main/core/src/test/java/bsky4j/bsky/feed/PostTest.java#L196-L204

```
FacetList list = FacetUtil.extractFacets(test);
List<RichtextFacet> facets = list.getRichTextFacets(...);

        BlueskyFactory
                .getInstance(Service.BSKY_SOCIAL.getUri())
                .feed().post(
                        FeedPostRequest.builder()
                                .accessJwt(accessJwt)
                                .facets(facets)
                                .text(list.getDisplayText())
                                .build()
                );
```

**Comment by tnaden** [comment]
Thank you, now it works as expected..!
Since I'm not interested in resolving handles I took one shortcut too many...
